calculate_votes_by_intervals:
  class: "Interval::CalculateVotesByInterval"
  queue: interval_value
  description: "This calculate votes by interval when there is a new vote."
remove_votes_by_intervals:
  class: "Interval::RemoveVotesByInterval"
  queue: interval_value
  description: "This calculate removes the intervals of a video."